[changelog]
header = ""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {{ commit.message | trim }} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/remi-deher/plex-rss/commit/{{ commit.id }}))
{%- endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = false
commit_parsers = [
  { message = "^feat", group = "✨ Nouveautés" },
  { message = "^fix", group = "🐛 Corrections" },
  { message = "^perf", group = "⚡ Performance" },
  { message = "^refactor", group = "♻️ Refactoring" },
  { message = "^docs", group = "📖 Documentation" },
  { message = "^chore", group = "🔧 Maintenance" },
  { message = "^ci", group = "👷 CI/CD" },
]
filter_commits = false
tag_pattern = "v[0-9]*"
