services:
  plex-rss:
    build: .
    container_name: plex-rss
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
      # - DATABASE_URL=postgresql://plexrss:plexrss@db:5432/plexrss

#   db:
#     image: postgres:15-alpine
#     container_name: plex-rss-db
#     environment:
#       POSTGRES_USER: plexrss
#       POSTGRES_PASSWORD: plexrss
#       POSTGRES_DB: plexrss
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     restart: unless-stopped
#
# volumes:
#   pgdata:

