<template>
  <div class="settings-grid">
    <section class="panel form-section"><div class="panel-head"><h2>Analyse VF</h2><button class="icon-button" title="Actualiser" @click="loadVff"><RefreshCw/></button></div><div class="status-stack"><span>Scan : {{ scanStatus.status||scanStatus.state||'inconnu' }}</span><span>Synchronisation Plex : {{ syncStatus.status||syncStatus.state||'inconnue' }}</span></div><div class="actions"><button class="secondary" @click="vff('/api/vff/scan?force=true')"><ScanSearch/>Scanner maintenant</button><button class="secondary" @click="vff('/api/vff/sync-plex')"><RefreshCw/>Synchroniser Plex</button></div></section>
    <section class="panel form-section"><div class="panel-head"><h2>Token API</h2><button class="icon-button" title="Actualiser" @click="loadSecrets"><RefreshCw/></button></div><code class="secret-box">{{ apiToken || (tokenActive ? 'Actif (valeur masquee)' : 'Aucun token genere') }}</code><div class="actions"><button class="secondary" @click="generateToken"><KeyRound/>Generer</button><button class="secondary danger" @click="deleteToken"><Trash2/>Revoquer</button></div><h2>Secret webhook</h2><code class="secret-box">{{ webhookSecret || (webhookActive ? 'Actif (valeur masquee)' : 'Aucun secret genere') }}</code><div class="actions"><button class="secondary" @click="generateWebhook"><KeyRound/>Generer</button><button class="secondary danger" @click="deleteWebhook"><Trash2/>Revoquer</button></div></section>
    <section class="panel form-section span-two"><div class="panel-head"><div><h2>Conflits de deduplication</h2><p>{{ conflicts.length }} element(s) a examiner.</p></div><div class="actions"><button class="secondary" @click="autoResolve"><WandSparkles/>Resolution automatique</button><button class="icon-button" title="Actualiser" @click="loadConflicts"><RefreshCw/></button></div></div><article v-for="group in conflicts" :key="group.key||group.tmdb_id" class="detail-row"><div><strong>{{ group.title||group.key||`TMDB ${group.tmdb_id}` }}</strong><span>{{ (group.entries||[]).length || 1 }} entree(s) · {{ group.type||'' }}</span></div><div class="actions"><button v-if="group.entries?.length" class="secondary" @click="resolve(group)">Fusionner</button><button v-if="group.type==='orphan'" class="secondary danger" @click="removeOrphan(group)"><Trash2/>Supprimer</button><button class="icon-button" title="Ignorer" @click="ignore(group)"><Check/></button></div></article><p v-if="!conflicts.length" class="empty">Aucun conflit detecte.</p></section>
    <section class="panel form-section span-two"><div class="panel-head"><h2>Problemes media</h2><button class="icon-button" title="Actualiser" @click="loadIssues"><RefreshCw/></button></div><article v-for="issue in issues" :key="issue.id" class="detail-row"><div><strong>{{ issue.media_title||issue.issue_type }}</strong><span>{{ issue.message||issue.issue_type }} · {{ issue.status }}</span></div><div class="actions"><button class="secondary" @click="updateIssue(issue,'investigating')">Prendre en charge</button><button class="secondary" @click="retryIssue(issue)"><RotateCcw/>Relancer</button><button class="secondary" @click="updateIssue(issue,'closed')"><Check/>Clore</button></div></article><p v-if="!issues.length" class="empty">Aucun signalement ouvert.</p></section>
  </div>
</template>
<script setup>
import { onMounted,ref } from 'vue';import { Check,KeyRound,RefreshCw,RotateCcw,ScanSearch,Trash2,WandSparkles } from '@lucide/vue';import { api } from '@/api';
const scanStatus=ref({}),syncStatus=ref({}),conflicts=ref([]),issues=ref([]),apiToken=ref(''),webhookSecret=ref(''),tokenActive=ref(false),webhookActive=ref(false);
async function loadVff(){[scanStatus.value,syncStatus.value]=await Promise.all([api('/api/vff/scan-status').catch(()=>({})),api('/api/vff/sync-status').catch(()=>({}))])}async function vff(path){await api(path,{method:'POST'});setTimeout(loadVff,1000)}
async function loadSecrets(){const [token,webhook]=await Promise.all([api('/api/settings/token').catch(()=>({})),api('/api/settings/webhook-secret').catch(()=>({}))]);tokenActive.value=Boolean(token.active);webhookActive.value=Boolean(webhook.active)}async function generateToken(){const data=await api('/api/settings/token',{method:'POST',body:JSON.stringify({scopes:['*']})});apiToken.value=data.api_token;tokenActive.value=true}async function deleteToken(){await api('/api/settings/token',{method:'DELETE'});apiToken.value='';tokenActive.value=false}async function generateWebhook(){const data=await api('/api/settings/webhook-secret',{method:'POST'});webhookSecret.value=data.webhook_secret;webhookActive.value=true}async function deleteWebhook(){await api('/api/settings/webhook-secret',{method:'DELETE'});webhookSecret.value='';webhookActive.value=false}
async function loadConflicts(){const data=await api('/api/conflicts');conflicts.value=[...(data.tmdb_conflicts||[]),...(data.orphaned||[]).map(x=>({...x,type:'orphan'})),...(data.long_pending||[]).map(x=>({...x,type:'pending'}))]}async function autoResolve(){await api('/api/conflicts/auto-resolve',{method:'POST'});await loadConflicts()}async function resolve(group){const entries=group.entries||[];if(entries.length<2)return;const keep=group.recommended_id||entries[0].id;await api('/api/conflicts/resolve',{method:'POST',body:JSON.stringify({keep_id:keep,delete_ids:entries.filter(x=>x.id!==keep).map(x=>x.id)})});await loadConflicts()}async function ignore(group){await api('/api/conflicts/ignore',{method:'POST',body:JSON.stringify({key:group.key})});await loadConflicts()}async function removeOrphan(group){if(!confirm(`Supprimer ${group.title} ?`))return;await api(`/api/conflicts/orphan/${group.id}`,{method:'DELETE'});await loadConflicts()}
async function loadIssues(){issues.value=await api('/api/media/issues')}async function updateIssue(issue,status){await api(`/api/media/issues/${issue.id}`,{method:'PATCH',body:JSON.stringify({status})});await loadIssues()}async function retryIssue(issue){await api(`/api/media/issues/${issue.id}/retry`,{method:'POST'});await loadIssues()}
onMounted(()=>Promise.all([loadVff(),loadSecrets(),loadConflicts(),loadIssues()]));
</script>
