"""add_email_subjects

Revision ID: 69815ec92e82
Revises: 0020
Create Date: 2026-06-15 23:05:20.783056

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "69815ec92e82"
down_revision: Union[str, None] = "0020"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("settings", sa.Column("email_request_subject", sa.String(), nullable=True))
    op.add_column("settings", sa.Column("email_available_subject", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settings", "email_available_subject")
    op.drop_column("settings", "email_request_subject")
    # ### end Alembic commands ###
