"""Add email templates fragments

Revision ID: a5c324f3ae2d
Revises: 0056_merge_email_templates
Create Date: 2026-07-11 04:26:04.927795

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a5c324f3ae2d'
down_revision: Union[str, None] = '0056_merge_email_templates'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('email_upgrade_template', sa.Text(), nullable=True))
    op.add_column('settings', sa.Column('email_upgrade_subject', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('email_fragment_subject_movie', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('email_fragment_subject_episode', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('email_fragment_subject_season_start', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('email_fragment_subject_season_complete', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('email_fragment_subject_series_complete', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('email_fragment_status_available', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('email_fragment_status_available_vo', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('email_fragment_status_available_vf', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('email_fragment_status_upgrade_vf', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('email_fragment_note_empty', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('email_fragment_note_vo_tracking', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('email_fragment_note_upgrade', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'email_fragment_note_upgrade')
    op.drop_column('settings', 'email_fragment_note_vo_tracking')
    op.drop_column('settings', 'email_fragment_note_empty')
    op.drop_column('settings', 'email_fragment_status_upgrade_vf')
    op.drop_column('settings', 'email_fragment_status_available_vf')
    op.drop_column('settings', 'email_fragment_status_available_vo')
    op.drop_column('settings', 'email_fragment_status_available')
    op.drop_column('settings', 'email_fragment_subject_series_complete')
    op.drop_column('settings', 'email_fragment_subject_season_complete')
    op.drop_column('settings', 'email_fragment_subject_season_start')
    op.drop_column('settings', 'email_fragment_subject_episode')
    op.drop_column('settings', 'email_fragment_subject_movie')
    op.drop_column('settings', 'email_upgrade_subject')
    op.drop_column('settings', 'email_upgrade_template')
    # ### end Alembic commands ###
