"""add email failure template settings

Revision ID: d0a28c3c1303
Revises: 0027
Create Date: 2026-06-17 10:26:59.074951

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd0a28c3c1303'
down_revision: Union[str, None] = '0027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('email_failure_template', sa.Text(), nullable=True))
    op.add_column('settings', sa.Column('email_failure_subject', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'email_failure_subject')
    op.drop_column('settings', 'email_failure_template')
    # ### end Alembic commands ###
