<template>
  <div class="page discover-page">
    <PageHeader title="Découvrir" description="Trouvez un média et voyez immédiatement s’il est disponible, demandé ou à découvrir."/>
    <section class="discover-command">
      <div class="discover-search"><Search/><input v-model="query" type="search" placeholder="Rechercher un film ou une série" aria-label="Rechercher un film ou une série" @input="scheduleSearch"><button class="filter-toggle" :class="{active:filtersOpen||activeFilterCount}" @click="filtersOpen=!filtersOpen"><SlidersHorizontal/>Filtres<span v-if="activeFilterCount">{{ activeFilterCount }}</span></button></div>
      <div class="discover-sections" aria-label="Sélection du catalogue"><button v-for="entry in sections" :key="entry.value" :class="{active:section===entry.value&&!query}" @click="setSection(entry.value)">{{ entry.label }}</button></div>
      <div class="discover-filters" :class="{open:filtersOpen}"><div class="segmented"><button v-for="entry in mediaTypes" :key="entry.value" :class="{active:mediaType===entry.value}" @click="setMediaType(entry.value)">{{ entry.label }}</button></div><select v-if="section==='genres'" v-model="genre" @change="load"><option value="">Tous les genres</option><option v-for="entry in genres" :key="entry.id" :value="entry.id">{{ entry.name }}</option></select><select v-model="availability"><option value="">Tous les états</option><option value="available">Disponible sur Plex</option><option value="requested">Déjà demandé</option><option value="new">À découvrir</option></select><button v-if="activeFilterCount" class="secondary" @click="resetFilters">Réinitialiser</button></div>
    </section>

    <div class="discover-heading"><div><span class="eyebrow">{{ query ? 'Résultats' : sectionLabel }}</span><h2>{{ query ? `Recherche « ${query} »` : sectionDescription }}</h2></div><span>{{ displayedItems.length }} média{{ displayedItems.length>1?'s':'' }}</span></div>
    <UiFeedback v-if="error" type="error" :message="error" retry @retry="load" />
    <UiFeedback v-if="loading" type="loading" message="Chargement du catalogue…"/>
    <template v-else>
      <section class="media-grid discover-grid">
        <article v-for="item in displayedItems" :key="`${item.media_type}:${item.tmdb_id||item.id}`" class="media-card discover-card" tabindex="0" @click="openDetail(item)" @keydown.enter="openDetail(item)">
          <div class="poster-shell"><img v-if="item.poster_url" :src="item.poster_url" alt="" loading="lazy"><div v-else class="poster-fallback"><Film/></div><div class="poster-badges"><span v-if="item.available||item.in_library" class="language-tag vf">Dans Plex</span><span v-else-if="item.requested" class="language-tag unknown">{{ statusLabel(item.request_status) }}</span><span v-else class="language-tag new-media">À découvrir</span></div><div class="poster-action">{{ item.available||item.in_library?'Voir la fiche':item.requested?'Suivre la demande':'Demander' }}</div></div>
          <div class="discover-card-info"><strong>{{ item.title||item.name }}</strong><span>{{ item.media_type==='show'?'Série':'Film' }}<template v-if="item.year"> · {{ item.year }}</template><template v-if="item.vote_average||item.vote"> · <Star/>{{ Number(item.vote_average||item.vote).toFixed(1) }}</template></span></div>
        </article>
      </section>
      <p v-if="!displayedItems.length" class="empty">Aucun média ne correspond à ces filtres.</p>
    </template>
  </div>
</template>
<script setup>
import { computed,onMounted,ref } from 'vue';import { Film,Search,SlidersHorizontal,Star } from '@lucide/vue';import { useRouter } from 'vue-router';import { api } from '@/api';import { mediaDetailPath } from '@/mediaUrl';
const router=useRouter();
const items=ref([]),query=ref(''),mediaType=ref('all'),section=ref('trending'),genre=ref(''),availability=ref(''),genres=ref([]),loading=ref(false),error=ref(''),filtersOpen=ref(!window.matchMedia('(max-width:640px)').matches);let timer;
const mediaTypes=[{value:'all',label:'Tout'},{value:'movie',label:'Films'},{value:'show',label:'Séries'}];const sections=[{value:'trending',label:'Tendances'},{value:'popular',label:'Populaires'},{value:'coming-soon',label:'Bientôt'},{value:'genres',label:'Par genre'}];
const sectionLabel=computed(()=>sections.find(entry=>entry.value===section.value)?.label||'Catalogue');
const sectionDescription=computed(()=>({trending:'Les médias qui attirent le plus l’attention',popular:'Les incontournables du moment','coming-soon':'Les prochaines sorties à surveiller',genres:'Explorez le catalogue par univers'})[section.value]);
const activeFilterCount=computed(()=>[mediaType.value!=='all',genre.value,availability.value].filter(Boolean).length);
const displayedItems=computed(()=>items.value.filter(item=>{if(availability.value==='available')return item.available||item.in_library;if(availability.value==='requested')return item.requested&&!item.available&&!item.in_library;if(availability.value==='new')return !item.requested&&!item.available&&!item.in_library;return true}));
function openDetail(item){const kind=item.library_id?'library':item.request_id?'request':'discover';router.push(mediaDetailPath(item,kind))}
function statusLabel(value){return ({pending_approval:'À approuver',pending:'En attente',sent_to_arr:'Transmise',partially_available:'Partiellement disponible',failed:'Échec',available:'Disponible'})[value]||'Demandé'}
function setMediaType(value){mediaType.value=value;if(value==='all'&&section.value==='genres')section.value='trending';loadGenres();load()}
function setSection(value){section.value=value;query.value='';load()}
function resetFilters(){mediaType.value='all';genre.value='';availability.value='';section.value='trending';load()}
async function loadGenres(){if(mediaType.value==='all')return;genres.value=await api(`/api/discover/genres?media_type=${mediaType.value}`).catch(()=>[])}
async function load(){loading.value=true;error.value='';try{const q=query.value.trim();if(q)items.value=await api(`/api/discover/search?query=${encodeURIComponent(q)}`);else if(section.value==='trending')items.value=await api(`/api/discover/trending?media_type=${mediaType.value}`);else if(section.value==='popular')items.value=await api(`/api/discover/popular?media_type=${mediaType.value==='all'?'movie':mediaType.value}`);else if(section.value==='coming-soon')items.value=await api(`/api/discover/coming-soon?media_type=${mediaType.value==='all'?'movie':mediaType.value}`);else{const type=mediaType.value==='all'?'movie':mediaType.value;items.value=await api(`/api/discover/discover?media_type=${type}${genre.value?`&genre=${genre.value}`:''}`)}}catch(e){error.value=e.message;items.value=[]}finally{loading.value=false}}
function scheduleSearch(){clearTimeout(timer);timer=setTimeout(load,300)}
onMounted(async()=>{await loadGenres();await load()});
</script>
<style scoped>
.discover-command{position:sticky;top:8px;z-index:20;display:grid;gap:9px;padding:12px;border:1px solid var(--border);border-radius:12px;background:color-mix(in srgb,var(--surface) 94%,transparent);backdrop-filter:blur(12px)}.discover-search{display:flex;align-items:center;gap:9px}.discover-search>svg{width:18px;color:var(--muted)}.discover-search input{flex:1;min-width:0;border:0;background:transparent;color:var(--text);font-size:15px;outline:0}.filter-toggle{display:flex;align-items:center;gap:6px;padding:7px 9px;border:1px solid var(--border);border-radius:8px;background:transparent;color:var(--muted)}.filter-toggle svg{width:15px}.filter-toggle span{padding:2px 5px;border-radius:999px;background:var(--accent);color:#111;font-size:9px}.filter-toggle.active{color:var(--text)}.discover-sections,.discover-filters{display:flex;align-items:center;gap:6px;overflow-x:auto}.discover-sections button{padding:6px 10px;border:0;border-radius:999px;background:transparent;color:var(--muted);white-space:nowrap}.discover-sections button.active{background:var(--accent);color:#111}.discover-filters{display:none;padding-top:8px;border-top:1px solid var(--border)}.discover-filters.open{display:flex}.discover-heading{display:flex;align-items:end;justify-content:space-between;gap:12px;margin-top:6px}.discover-heading>div{display:grid;gap:2px}.discover-heading h2{margin:0;font-size:17px}.discover-heading>span{color:var(--muted);font-size:10px}.discover-grid{align-items:start}.discover-card{cursor:pointer}.poster-badges{position:absolute;top:7px;left:7px;display:grid;gap:4px}.new-media{background:rgba(15,23,42,.85);color:#fff}.poster-action{position:absolute;inset:auto 7px 7px;padding:7px;border-radius:7px;background:rgba(10,10,10,.82);color:#fff;font-size:10px;font-weight:700;text-align:center;opacity:0;transform:translateY(5px);transition:.2s}.discover-card:hover .poster-action,.discover-card:focus .poster-action{opacity:1;transform:none}.discover-card-info{display:grid;gap:4px}.discover-card-info>span{display:flex;align-items:center;color:var(--muted);font-size:10px}.discover-card-info svg{width:11px;height:11px;margin-left:3px;color:var(--accent)}@media(max-width:640px){.discover-command{top:6px;padding:10px}.filter-toggle{font-size:0}.filter-toggle span{font-size:9px}.discover-filters{align-items:stretch;flex-direction:column;overflow:visible}.discover-filters .segmented{display:flex}.discover-filters .segmented button{flex:1}.discover-filters select{width:100%}.poster-action{display:none}.discover-heading h2{font-size:14px}}
</style>
