<template>
  <div class="page"><header class="page-head"><div><h1>Profil</h1><p>Informations, mot de passe et methodes de connexion.</p></div></header><p v-if="error" class="notice error-text">{{ error }}</p><p v-if="message" class="notice success-text">{{ message }}</p>
    <div class="settings-grid">
      <section class="panel form-section"><h2>Compte</h2><div class="account-summary"><strong>{{ identity?.custom_name||identity?.display_name||identity?.plex_user_id||identity?.username }}</strong><span class="badge">{{ identity?.role }}</span><p>{{ identity?.plex_email||identity?.notification_email||'Aucun email renseigne' }}</p><code>{{ identity?.plex_user_id }}</code></div><label>Nouveau mot de passe<input v-model="password" type="password" minlength="8" autocomplete="new-password"></label><button class="primary" :disabled="password.length<8||busy" @click="changePassword"><KeyRound/>Modifier</button></section>
      <section class="panel form-section"><h2>Double authentification</h2><img v-if="totpQr" :src="totpQr" class="totp-qr" alt="QR code TOTP"><p v-if="totpSecret">Secret : <code>{{ totpSecret }}</code></p><button v-if="!totpSecret" class="secondary" :disabled="busy" @click="setupTotp"><ShieldCheck/>Configurer</button><template v-else><label>Code a 6 chiffres<input v-model="totpCode" inputmode="numeric" maxlength="6"></label><button class="primary" :disabled="totpCode.length!==6||busy" @click="enableTotp">Activer</button></template><button class="secondary danger" :disabled="busy" @click="disableTotp">Desactiver le TOTP</button></section>
      <section class="panel form-section"><div class="panel-head"><h2>Passkeys</h2><button class="icon-button" title="Actualiser" @click="loadPasskeys"><RefreshCw/></button></div><button class="secondary" :disabled="busy||!webAuthnAvailable" @click="registerPasskey"><Fingerprint/>Enregistrer une passkey</button><div v-for="key in passkeys" :key="key.credential_id" class="inline-row"><div><strong>{{ key.name }}</strong><span>{{ formatDate(key.created_at) }}</span></div><button class="icon-button danger" title="Supprimer" @click="deletePasskey(key)"><Trash2/></button></div><p v-if="!passkeys.length">Aucune passkey enregistree.</p></section>
    </div>
  </div>
</template>
<script setup>
import { onMounted,ref } from 'vue';import { Fingerprint,KeyRound,RefreshCw,ShieldCheck,Trash2 } from '@lucide/vue';import QRCode from 'qrcode';import { api } from '@/api';
const identity=ref(null),password=ref(''),totpSecret=ref(''),totpCode=ref(''),totpQr=ref(''),passkeys=ref([]),busy=ref(false),error=ref(''),message=ref('');const webAuthnAvailable=Boolean(window.PublicKeyCredential&&navigator.credentials);
function notify(text){message.value=text;error.value=''}function formatDate(value){return value?new Intl.DateTimeFormat('fr-FR',{dateStyle:'medium'}).format(new Date(value)):'-'}
async function load(){try{identity.value=await api('/api/session');await loadPasskeys()}catch(e){error.value=e.message}}async function loadPasskeys(){if(!identity.value?.id)return;try{passkeys.value=await api(`/api/users/${identity.value.id}/passkeys`)}catch(e){error.value=e.message}}
async function changePassword(){busy.value=true;try{await api(`/api/users/${identity.value.id}/password`,{method:'POST',body:JSON.stringify({password:password.value})});password.value='';notify('Mot de passe modifie.')}catch(e){error.value=e.message}finally{busy.value=false}}
async function setupTotp(){busy.value=true;try{const data=await api(`/api/users/${identity.value.id}/totp/setup`,{method:'POST'});totpSecret.value=data.secret;totpQr.value=await QRCode.toDataURL(data.uri,{width:220,margin:1});notify('Scannez le QR code dans votre application d’authentification.')}catch(e){error.value=e.message}finally{busy.value=false}}
async function enableTotp(){busy.value=true;try{await api(`/api/users/${identity.value.id}/totp/enable`,{method:'POST',body:JSON.stringify({code:totpCode.value})});totpSecret.value='';totpCode.value='';totpQr.value='';notify('Double authentification activee.')}catch(e){error.value=e.message}finally{busy.value=false}}
async function disableTotp(){busy.value=true;try{await api(`/api/users/${identity.value.id}/totp`,{method:'DELETE'});totpSecret.value='';totpQr.value='';notify('Double authentification desactivee.')}catch(e){error.value=e.message}finally{busy.value=false}}
async function deletePasskey(key){try{await api(`/api/users/${identity.value.id}/passkeys/${encodeURIComponent(key.credential_id)}`,{method:'DELETE'});await loadPasskeys()}catch(e){error.value=e.message}}
function decode(value){const normalized=value.replace(/-/g,'+').replace(/_/g,'/');const binary=atob(normalized.padEnd(Math.ceil(normalized.length/4)*4,'='));return Uint8Array.from(binary,char=>char.charCodeAt(0)).buffer}function encode(value){const bytes=new Uint8Array(value);let binary='';bytes.forEach(byte=>binary+=String.fromCharCode(byte));return btoa(binary).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function registerPasskey(){busy.value=true;error.value='';try{const options=await api('/api/users/webauthn/register/options',{method:'POST',body:JSON.stringify({user_id:identity.value.id})});options.challenge=decode(options.challenge);options.user.id=decode(options.user.id);options.excludeCredentials=(options.excludeCredentials||[]).map(entry=>({...entry,id:decode(entry.id)}));const credential=await navigator.credentials.create({publicKey:options});const payload=credential.toJSON?credential.toJSON():{id:credential.id,rawId:encode(credential.rawId),type:credential.type,response:{clientDataJSON:encode(credential.response.clientDataJSON),attestationObject:encode(credential.response.attestationObject)},clientExtensionResults:credential.getClientExtensionResults()};const name=prompt('Nom de la passkey','Passkey')||'Passkey';await api('/api/users/webauthn/register/verify',{method:'POST',body:JSON.stringify({user_id:identity.value.id,credential:payload,name})});await loadPasskeys();notify('Passkey enregistree.')}catch(e){error.value=e.message}finally{busy.value=false}}
onMounted(load);
</script>
