<template>
  <div class="page">
    <header class="page-head"><div><h1>Demandes</h1><p>Validation, suivi et traitement des demandes.</p></div><div class="actions"><button v-if="isAdmin" class="secondary" :disabled="busy" @click="runUtility('/api/requests/poll')"><RefreshCw/>Verifier maintenant</button><button class="icon-button" :disabled="loading" title="Actualiser" @click="load"><RefreshCw :class="{spin:loading}"/></button></div></header>
    <div class="toolbar wrap"><input v-model="query" class="search" type="search" placeholder="Rechercher un titre" @input="scheduleLoad"><select v-model="status"><option value="">Tous les statuts</option><option v-for="value in statuses" :key="value" :value="value">{{ label(value) }}</option></select><select v-model="type"><option value="">Tous les types</option><option value="movie">Films</option><option value="show">Series</option></select><select v-model="source"><option value="">Toutes les sources</option><option v-for="value in sources" :key="value">{{ value }}</option></select></div>
    <div v-if="isAdmin&&selectedIds.length" class="bulk-bar"><strong>{{ selectedIds.length }} selectionnee(s)</strong><button class="secondary" @click="bulk('retry')"><RotateCcw/>Relancer</button><button class="secondary" @click="bulk('mark-processed')"><CheckCheck/>Traiter</button><button class="secondary danger" @click="bulk('delete')"><Trash2/>Supprimer</button><button class="icon-button" title="Annuler" @click="selectedIds=[]"><X/></button></div>
    <p v-if="error" class="notice error-text">{{ error }}</p>
    <section class="panel table-wrap"><table><thead><tr><th v-if="isAdmin"><input type="checkbox" :checked="allSelected" @change="toggleAll"></th><th>Titre</th><th>Type</th><th>Demandeur</th><th>Source</th><th>Statut</th><th>Date</th><th></th></tr></thead><tbody><tr v-for="row in filtered" :key="row.id" @dblclick="detail=row"><td v-if="isAdmin"><input v-model="selectedIds" type="checkbox" :value="row.id"></td><td><button class="text-button" @click="detail=row"><strong>{{ row.title }}</strong><small v-if="row.year">{{ row.year }}</small></button></td><td>{{ row.media_type==='show'?'Serie':'Film' }}</td><td>{{ row.requested_by||row.plex_user||row.plex_user_id }}</td><td>{{ row.source||'-' }}</td><td><span class="badge" :class="row.status">{{ label(row.status) }}</span></td><td>{{ formatDate(row.requested_at) }}</td><td class="actions"><button v-if="row.status==='pending_approval'&&isAdmin" class="icon-button success" title="Approuver" @click="act(row,'approve')"><Check/></button><button v-if="row.status==='pending_approval'&&isAdmin" class="icon-button danger" title="Refuser" @click="reject(row)"><Ban/></button><button v-if="row.arr_id" class="icon-button" title="Rechercher une release" @click="router.push(`/releases/${row.id}`)"><Search/></button><button v-if="row.status==='failed'&&isAdmin" class="icon-button" title="Relancer" @click="act(row,'retry')"><RotateCcw/></button><button v-if="row.status!=='available'" class="icon-button danger" title="Annuler" @click="act(row,'cancel')"><X/></button></td></tr></tbody></table><p v-if="!loading&&!filtered.length" class="empty">Aucune demande.</p></section>
    <MediaDetailDrawer v-if="detail" :item="detail" mode="request" @close="detail=null" @updated="load"/>
  </div>
</template>
<script setup>
import { computed,onMounted,onUnmounted,ref } from 'vue';import { Ban,Check,CheckCheck,RefreshCw,RotateCcw,Search,Trash2,X } from '@lucide/vue';import { useRoute, useRouter } from 'vue-router';import { api } from '@/api';import { useRealtime } from '@/events';import MediaDetailDrawer from '@/components/MediaDetailDrawer.vue';
const route=useRoute();const rows=ref([]),query=ref(route.query.query||''),status=ref(route.query.status||''),type=ref(route.query.type||''),source=ref(''),selectedIds=ref([]),detail=ref(null),loading=ref(false),busy=ref(false),error=ref(''),isAdmin=ref(false);const router=useRouter();let timer,fallback;
const statuses=['pending_approval','pending','sent_to_arr','available','failed','rejected'];const sources=computed(()=>[...new Set(rows.value.map(x=>x.source).filter(Boolean))]);const filtered=computed(()=>rows.value.filter(row=>(!status.value||row.status===status.value)&&(!type.value||row.media_type===type.value)&&(!source.value||row.source===source.value)));const allSelected=computed(()=>filtered.value.length&&filtered.value.every(x=>selectedIds.value.includes(x.id)));
function label(value){return ({pending_approval:'A approuver',pending:'En attente',sent_to_arr:'Transmise',available:'Disponible',failed:'Echec',rejected:'Refusee'})[value]||value}function formatDate(value){return value?new Intl.DateTimeFormat('fr-FR',{dateStyle:'medium'}).format(new Date(value)):'-'}function scheduleLoad(){clearTimeout(timer);timer=setTimeout(load,250)}function toggleAll(event){selectedIds.value=event.target.checked?filtered.value.map(x=>x.id):[]}
async function load(){loading.value=true;error.value='';try{rows.value=await api(`/api/requests${query.value.trim()?`?query=${encodeURIComponent(query.value.trim())}`:''}`);selectedIds.value=selectedIds.value.filter(id=>rows.value.some(x=>x.id===id))}catch(e){error.value=e.message}finally{loading.value=false}}
async function act(row,action){busy.value=true;try{if(action==='cancel'&&isAdmin.value)await api(`/api/requests/${row.id}`,{method:'DELETE'});else await api(`/api/requests/${row.id}/${action}`,{method:'POST'});await load()}catch(e){error.value=e.message}finally{busy.value=false}}
async function reject(row){const reason=prompt('Motif du refus','Demande refusee par un administrateur');if(reason===null)return;busy.value=true;try{await api(`/api/requests/${row.id}/reject`,{method:'POST',body:JSON.stringify({reason})});await load()}catch(e){error.value=e.message}finally{busy.value=false}}
async function bulk(action){if(action==='delete'&&!confirm(`Supprimer ${selectedIds.value.length} demandes ?`))return;busy.value=true;try{await api(`/api/requests/bulk/${action}`,{method:'POST',body:JSON.stringify({ids:selectedIds.value,delete_from_arr:false,delete_files:false})});selectedIds.value=[];await load()}catch(e){error.value=e.message}finally{busy.value=false}}
async function runUtility(path){busy.value=true;try{await api(path,{method:'POST'});await load()}catch(e){error.value=e.message}finally{busy.value=false}}
useRealtime(['request.updated'],load);onMounted(async()=>{const session=await api('/api/session').catch(()=>null);isAdmin.value=Boolean(session?.is_owner||session?.role==='admin');await load();fallback=setInterval(load,120000)});onUnmounted(()=>{clearTimeout(timer);clearInterval(fallback)});
</script>
